# Generated by Django 5.2.11 on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#60A5FA', max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='🏷️', max_length=8),
        ),
    ]
